# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f6f2f4c5c58a9e4b82c9e47c0afc62e50409425cee8cd6934b2890e3275d96e7cf5305d86b95f85becb0b18b5601b4bf25717f224a6b951164ff33f4c4cbd7d

test:
  secret_key_base: f702622f1fa1fb3e2efec39745ccec5551e4ae2325bc9c0e77eecfecd1f8cc292ca5a405b8087ae8ecbe5a489c90dc2901790155042069246d729ff493d3221c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
